change Notify when to Notify once
tiagoporto/generator-swill-boilerplate pull request #36
Opened 2016-10-15 04:05 UTC by bituka

My wife told me that it is better to use once instead when in one of the bullet points

2016-10-15 04:12 UTC, bituka commented
As the other steps have no "s", this needs to change for uniformity.

2016-10-15 18:49 UTC, tiagoporto requested changes
There some changes now, please resolve the conflicts to merge.
Thanks

2016-10-15 18:49 UTC, tiagoporto commented on README.md
> +* Notify once tasks are complete
The sentence now is Notifies when tasks are complete.
Can you confirm the `once` use please.

2016-10-16 09:02 UTC, bituka commented
I think this seems fine now.

2016-10-16 09:02 UTC, closed without merging